### ISSUE TITLE
Feature: lever/button protection

### ISSUE THREAD

**Issue by daemitus** [md-5/Deadbolt#6]
Protection of onuse including breakage perhaps?

**Comment by md-5** [comment]
Thats a great idea but will require a complete rework of redstone protection. Deadbolt 2.0 feature.
Sound like a thing that craftbook might try as well :)

**Comment by daemitus** [comment]
Not really, it would just require an onPlayerInteract block.gettype=button or lever
the difficult part would be doing sign finding logic and where the signs will go.

**Comment by md-5** [comment]
Yeah but at the moment all redstone interaction is blocked to protected doors. This would allow private circuits as such, but not automatic redstone opening of doors, in the current implementations state

**Comment by md-5** [comment]
I think that the trapdoor and a bit of the door logic could make this work. The other point im trying to get across is that private doors cannot be opened by ANY redstone. Defniately v2.0 feature though.

**Comment by daemitus** [comment]
Tracing where the redstone current came from is a nightmare. The idea would be to just have an external button on a wall you could protect, to trigger say, a piston door. Where the button would be protected.

**Comment by md-5** [comment]
So the feature request should be changed to button and lever interact protection, with a disclaimer that this would not allow redstone activated private doors. ie just make sure the user knows to not private the door, although this brings back the issue of placing redstone torches / extra buttons. So i guess the feature request is then redstone circuit protection.

**Comment by daemitus** [comment]
I really dont want to touch circuit protection. not at all. Youd have to start from every single input and follow it to completion, branching the entire path and checking for protection on every block. Extremely ugly and intensive.

**Comment by md-5** [comment]
Im not really being too clear on this. Pretty much icall it circut protection because you can have an autonatic harvester with all circutry concealed and then 1 harvest button. You private the button and then it is protected because no one can hsrvest without placing their own button or torch. And because it is now private they would probably get banned for griefing. Same as deadbolt doesnt protect the house just the door. You can still bypass the door by griefing he wall. Same principle with button protection. There are simply no ways to activate the circuit withiout placing or breaking
